package tools.activist.enums;

public class Heading {
  public enum Calendar {
    CALENDAR_MAJOR_HOUSE_SECOND("MAJOR STATE CALENDAR HOUSE BILLS SECOND READING"),
    CALENDAR_MAJOR_HOUSE_THIRD("MAJOR STATE CALENDAR HOUSE BILLS THIRD READING"),
    CALENDAR_MAJOR_SENATE_SECOND("MAJOR STATE CALENDAR SENATE BILLS SECOND READING"),
    CALENDAR_MAJOR_SENATE_THIRD("MAJOR STATE CALENDAR SENATE BILLS THIRD READING"),
    CALENDAR_GENERAL_HOUSE_SECOND("GENERAL STATE CALENDAR HOUSE BILLS SECOND READING"),
    CALENDAR_GENERAL_HOUSE_THIRD("GENERAL STATE CALENDAR HOUSE BILLS THIRD READING"),
    CALENDAR_GENERAL_SENATE_SECOND("GENERAL STATE CALENDAR SENATE BILLS SECOND READING"),
    CALENDAR_GENERAL_SENATE_THIRD("GENERAL STATE CALENDAR SENATE BILLS THIRD READING"),
    CALENDAR_LNC_HOUSE_SECOND("LOCAL, CONSENT, AND RESOLUTIONS CALENDAR SECOND READING"),
    CALENDAR_LNC_HOUSE_THIRD("LOCAL, CONSENT, AND RESOLUTIONS CALENDAR THIRD READING"),
    CALENDAR_LNC_SENATE_SECOND("LOCAL, CONSENT, AND RESOLUTIONS CALENDAR SENATE BILLS SECOND READING"),
    CALENDAR_LNC_SENATE_THIRD("LOCAL, CONSENT, AND RESOLUTIONS CALENDAR SENATE BILLS THIRD READING"),
    CALENDAR_EMERGENCY_HOUSE_SECOND("EMERGENCY CALENDAR HOUSE BILLS SECOND READING"),
    CALENDAR_EMERGENCY_HOUSE_THIRD("EMERGENCY CALENDAR HOUSE BILLS THIRD READING"),
    CALENDAR_EMERGENCY_SENATE_SECOND("EMERGENCY CALENDAR SENATE BILLS SECOND READING"),
    CALENDAR_EMERGENCY_SENATE_THIRD("EMERGENCY CALENDAR SENATE BILLS THIRD READING"),
    CALENDAR_CONSTITUTIONAL_HOUSE_SECOND("CONSTITUTIONAL AMENDMENTS CALENDAR HOUSE JOINT RESOLUTIONS SECOND READING"),
    CALENDAR_CONSTITUTIONAL_HOUSE_THIRD("CONSTITUTIONAL AMENDMENTS CALENDAR HOUSE JOINT RESOLUTIONS THIRD READING"),
    CALENDAR_CONSTITUTIONAL_SENATE_SECOND("CONSTITUTIONAL AMENDMENTS CALENDAR SENATE JOINT RESOLUTIONS SECOND READING"),
    CALENDAR_CONSTITUTIONAL_SENATE_THIRD("CONSTITUTIONAL AMENDMENTS CALENDAR SENATE JOINT RESOLUTIONS THIRD READING"),
    CALENDAR_HOUSE_SECOND("HOUSE BILLS SECOND READING"), CALENDAR_HOUSE_THIRD("HOUSE BILLS THIRD READING"),
    CALENDAR_RESOLUTIONS("RESOLUTIONS CALENDAR"),
    CALENDAR_CONGRATULATORY_MEMORIAL("CONGRATULATORY AND MEMORIAL CALENDAR");

    private String heading;

    Calendar(String heading) {
      this.heading = heading;
    }

    public String getHeading() {
      return heading;
    }

    public static boolean contains(String test) {
      for (Calendar c : Calendar.values()) {
        if (c.getHeading().equals(test))
          return true;
      }
      return false;
    }

    public String toString() {
      return heading;
    }
  }

  public enum Motion {
    MOTION_PROVIDE_SUSPEND_FIVE_DAY_RULE("MOTION TO SUSPEND FIVE-DAY POSTING RULE"),
    MOTION_PROVIDE_SUSPEND_LOCAL_RULES("PROVIDING FOR A LOCAL, CONSENT, AND RESOLUTIONS RULES SUSPENDED"),
    MOTION_PROVIDE_SUSPEND_LOCAL_CALENDAR_RULES(
        "PROVIDING FOR A LOCAL, CONSENT, AND RESOLUTIONS CALENDAR RULES SUSPENDED"),
    MOTION_PROVIDE_LOCAL_CALENDAR("PROVIDING FOR A LOCAL, CONSENT, AND RESOLUTIONS CALENDAR"),
    MOTION_PROVIDE_ADDENDUM_LOCAL_CALENDAR("PROVIDING FOR AN ADDENDUM TO LOCAL, CONSENT, AND RESOLUTIONS CALENDAR"),
    MOTION_PROVIDE_MEMORIAL_CALENDAR("PROVIDING FOR A CONGRATULATORY AND MEMORIAL CALENDAR"),
    MOTION_PROVIDE_SINE_DIE("PROVIDING FOR ADJOURNMENT SINE DIE"), MOTION_PROVIDE_RECESS("PROVIDING FOR RECESS"),
    MOTION_PROVIDE_ADJOURN("PROVIDING FOR ADJOURNMENT"), MOTION_RECORD_VOTE("MOTION FOR ONE RECORD VOTE"),
    MOTION_BILLS_RECOMMITTED("BILLS RECOMMITTED"),
    MOTION_SUSPEND_LOCAL_CALENDAR_RULES("LOCAL, CONSENT, AND RESOLUTIONS CALENDAR MOTION TO SUSPEND RULES"),
    MOTION_COMMITTEE_MEET("COMMITTEE GRANTED PERMISSION TO MEET"),
    MOTION_COMMITTEES_MEET("COMMITTEES GRANTED PERMISSION TO MEET");

    private String heading;

    Motion(String heading) {
      this.heading = heading;
    }

    public String getHeading() {
      return heading;
    }

    public static boolean contains(String test) {
      for (Motion c : Motion.values()) {
        if (c.getHeading().equals(test))
          return true;
      }
      return false;
    }

    public String toString() {
      return heading;
    }
  }

  public enum Announcement {
    SIGNED_BY_GOVERNOR("SIGNED BY THE GOVERNOR"), VETOED_BY_GOVERNOR("VETOED BY THE GOVERNOR"),
    MESSAGE_GOVERNOR("MESSAGE FROM THE GOVERNOR OF THE STATE OF TEXAS"),
    FILED_BY_GOVERNOR("FILED WITHOUT THE GOVERNOR\'S SIGNATURE"), SENT_TO_GOVERNOR("SENT TO THE GOVERNOR"),
    ENROLLED("ENROLLED"), ENGROSSED("ENGROSSED"), MESSAGE_SENATE("MESSAGE FROM THE SENATE"),
    MESSAGES_SENATE("MESSAGES FROM THE SENATE"), SIGNED_BY_SPEAKER("SIGNED BY THE SPEAKER"),
    FILED_RECOMMENDATIONS("RECOMMENDATIONS FILED WITH THE SPEAKER"), REFERRED_COMMITTEE("REFERRED TO COMMITTEES"),
    REFERRED_RESOLUTIONS_COMMITTEE("RESOLUTIONS REFERRED TO COMMITTEES"),
    REFERRED_CORRECTION("CORRECTIONS IN REFERRAL"), NOTICE_GIVEN("NOTICE GIVEN"),
    NOTICE_SENT_SOS("SENT TO THE SECRETARY OF THE STATE"), NOTICE_ROLL("ROLL OF HOUSE"),
    NOTICE_STANDING_COMMITTEE_REPORTS("STANDING COMMITTEE REPORTS"), NOTICE_RECESS("RECESS"),
    NOTICE_ADJOURN_SINE_DIE("ADJOURNMENT SINE DIE"), NOTICE_ADJOURN("ADJOURNMENT"),
    NOTICE_DAILY_PHYSICIAN("CAPITOL PHYSICIAN"), NOTICE_DAILY_INTERPRETER_DEAF("INTERPRETER FOR THE DEAF"),
    NOTICE_GUESTS("INTRODUCTION OF GUESTS"), NOTICE_LEAVE_OF_ABSENCE("LEAVE OF ABSENCE GRANTED"),
    NOTICE_LEAVES_OF_ABSENCE("LEAVES OF ABSENCE GRANTED"), NOTICE_COMMITTEE_MEETING("COMMITTEE MEETING ANNOUNCEMENT"),
    NOTICE_COMMITTEE_MEETINGS("COMMITTEE MEETING ANNOUNCEMENTS"),
    NOTICE_SIGNED_BY_SPEAKER("BILLS AND RESOLUTIONS SIGNED BY THE SPEAKER"), ADOPT_RESOLUTION("RESOLUTIONS ADOPTED"),
    VOTE_REASON("REASON FOR VOTE"), VOTE_REASONS("REASONS FOR VOTE"), VOTE_STATEMENT("STATEMENT OF VOTE"),
    VOTE_STATEMENTS("STATEMENTS OF VOTE"), BUSINESS_POSTPONED("POSTPONED BUSINESS"),
    BUSINESS_SUSPENDED("REGULAR ORDER OF BUSINESS SUSPENDED"),
    LOCAL_SUSPENDED("LOCAL, CONSENT, AND RESOLUTIONS CALENDAR RULES SUSPENDED"),
    CONSTITUTIONAL_RULE_SUSPENDED("CONSTITUTIONAL RULE SUSPENDED"),
    FIVE_DAY_RULE_SUSPENDED("FIVE-DAY POSTING RULE SUSPENDED"), RULES_SUSPENDED("RULES SUSPENDED"),
    ORDERED_PRINTED("REMARKS ORDERED PRINTED"), PARLIAMENTARY_INQUIRY("PARLIAMENTARY INQUIRY"),
    HOUSE_AT_EASE("HOUSE AT EASE"), AFTERNOON_SESSION("AFTERNOON SESSION");

    private String heading;

    Announcement(String heading) {
      this.heading = heading;
    }

    public String getHeading() {
      return heading;
    }

    public static boolean contains(String test) {
      for (Announcement c : Announcement.values()) {
        if (c.getHeading().equals(test))
          return true;
      }
      return false;
    }

    public String toString() {
      return heading;
    }
  }
}
